2018-12-08 12:42:55.737 [error] <0.430.0>@gproc:reg CRASH REPORT Process <0.430.0> with 0 neighbours crashed with reason: call to undefined function gproc:reg({p,l,interesting_stuff})
2018-12-08 12:42:55.738 [error] <0.429.0>@gproc:reg Supervisor skye_sup had child soj_server started with soj_server:start_link(test) at undefined exit with reason call to undefined function gproc:reg({p,l,interesting_stuff}) in context start_error
2018-12-08 12:42:55.739 [error] <0.427.0> CRASH REPORT Process <0.427.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,soj_server,{undef,[{gproc,reg,[{p,l,interesting_stuff}],[]},{soj_server,init,1,[{file,"/Users/lc/IdeaProjects/Skye/_build/default/deps/skye/src/soj_server.erl"},{line,76}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}},{skye_app,start,[normal,[]]}} in application_master:init/4 line 138
